#ifndef KERNEL_KB_H
#define KERNEL_KB_H

#define NUM_KEYS 128

#include <stdint.h>

typedef enum {
    KEY_NULL = 0,
    KEY_ESCAPE,
    KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0,
    KEY_MINUS, KEY_EQUALS,
    KEY_BACKSPACE,
    KEY_TAB,
    KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P,
    KEY_LEFT_BRACKET, KEY_RIGHT_BRACKET,
    KEY_ENTER,
    KEY_CONTROL,
    KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L,
    KEY_SEMICOLON, KEY_APOSTROPHE, KEY_BACKTICK,
    KEY_LEFT_SHIFT,
    KEY_BACKSLASH,
    KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M,
    KEY_COMMA, KEY_PERIOD, KEY_SLASH,
    KEY_RIGHT_SHIFT,
    KEY_ASTERISK,
    KEY_ALT,
    KEY_SPACE,
    KEY_CAPS_LOCK,
    KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10,
    KEY_NUM_LOCK, KEY_SCROLL_LOCK,
    KEY_HOME,
    KEY_UP, KEY_PAGE_UP,
    KEY_UNKNOWN0,
    KEY_LEFT,
    KEY_UNKNOWN1,
    KEY_RIGHT,
    KEY_PLUS,
    KEY_END,
    KEY_DOWN, KEY_PAGE_DOWN,
    KEY_INSERT,
    KEY_DELETE,
    KEY_UNKNOWN2, KEY_UNKNOWN3, KEY_UNKNOWN4,
    KEY_F11, KEY_F12,
    KEY_UNDEFINED
} KeyCode_T;

char kb_get_char(uint8_t scan_code);

#endif
